// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJWrOUk8yBpQcrTVz-tSqvlHE03CRJDa8',
    appId: '1:755593807401:web:530dc3a80218bdcbb43e38',
    messagingSenderId: '755593807401',
    projectId: 'zzzwall',
    authDomain: 'zzzwall.firebaseapp.com',
    storageBucket: 'zzzwall.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATdiOVAe2fbgdoxsFfdf140tQ-QxBVUQE',
    appId: '1:755593807401:android:4ca44181d24e964db43e38',
    messagingSenderId: '755593807401',
    projectId: 'zzzwall',
    storageBucket: 'zzzwall.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpH4Crlsimw68hnT3DM_vgwjcjnn3VApo',
    appId: '1:755593807401:ios:08b3f12ce08e98d3b43e38',
    messagingSenderId: '755593807401',
    projectId: 'zzzwall',
    storageBucket: 'zzzwall.appspot.com',
    iosBundleId: 'com.example.zzzwall',
  );
}
